# Generated by Django 5.2.6 on 2025-09-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
